### ISSUE TITLE
cisco.mso.mso_schema_template_anp_epg_contract producing UnboundLocalError when querying EPG with no contracts (DCNE-166)

### ISSUE THREAD

**Issue by justinbrink** [CiscoDevNet/ansible-mso#523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Running a query to mso_schema_template_anp_epg_contract with no contract or contracts specified, will return an UnboundLocalError when trying to access contract_ref (undefined) in plugins/modules/mso_schema_template_anp_epg_contract.py line 354. 

### Affected Module Name(s):

* cisco.mso.mso_schema_template_anp_epg_contract

### MSO version and MSO Platform

* any

### APIC version and APIC Platform for Site Level Resources

* any

### Collection versions

* cisco.mso 2.9.0

### Output/ Error message

```The full traceback is:
Traceback (most recent call last):
  File "/Users/jbrink/.ansible/tmp/ansible-local-9280142kc74ki/ansible-tmp-1724359497.482809-92913-215026567338156/AnsiballZ_mso_schema_template_anp_epg_contract.py", line 259, in <module>
    _ansiballz_main()
  File "/Users/jbrink/.ansible/tmp/ansible-local-9280142kc74ki/ansible-tmp-1724359497.482809-92913-215026567338156/AnsiballZ_mso_schema_template_anp_epg_contract.py", line 249, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/jbrink/.ansible/tmp/ansible-local-9280142kc74ki/ansible-tmp-1724359497.482809-92913-215026567338156/AnsiballZ_mso_schema_template_anp_epg_contract.py", line 122, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.mso.plugins.modules.mso_schema_template_anp_epg_contract', init_globals=dict(_module_fqn='ansible_collections.cisco.mso.plugins.modules.mso_schema_template_anp_epg_contract', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/x4/lfbrl1gj5hb178gchm8df2dh0000gn/T/ansible_cisco.mso.mso_schema_template_anp_epg_contract_payload_bhz7s79i/ansible_cisco.mso.mso_schema_template_anp_epg_contract_payload.zip/ansible_collections/cisco/mso/plugins/modules/mso_schema_template_anp_epg_contract.py", line 449, in <module>
  File "/var/folders/x4/lfbrl1gj5hb178gchm8df2dh0000gn/T/ansible_cisco.mso.mso_schema_template_anp_epg_contract_payload_bhz7s79i/ansible_cisco.mso.mso_schema_template_anp_epg_contract_payload.zip/ansible_collections/cisco/mso/plugins/modules/mso_schema_template_anp_epg_contract.py", line 345, in main
UnboundLocalError: cannot access local variable 'contract_ref' where it is not associated with a value
```

### Expected Behavior

* When no contract or contracts variables are provided, return a list of only existing contracts assigned to the EPG or an empty list if there are none

### Actual Behavior

* When no contract or contracts variables are provided, and the EPG has no assigned contracts, the error message provided is trying to access contract_ref and contract.type, as if the contract was provided. This check should only be run if contract is not null, and return [] otherwise

### Playbook tasks to Reproduce

```- name: MSO EPG TO CONTRACT
  cisco.mso.mso_schema_template_anp_epg_contract:
    hostname: "{{ mso_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_pass }}"
    validate_certs: "{{ validate_certs }}"
    schema: "{{ schema }}"
    template: "{{ template }}"
    anp: "{{ app_profile }}"
    epg: "{{ name_of_epg_with_no_contracts }}"
    state: "query"
```

The fix is easy and I can provide a PR if needed:
```    if state == "query":
        if contracts:
            if len(found_contracts) == len(contracts):
                mso.existing = found_contracts
            else:
                not_found_contracts = [
                    "Contract with Reference '{0}' and type '{1}' not found".format(mso.contract_ref(**contract), contract.get("type"))
                    for contract in contracts
                    if contract not in found_contracts
                ]
                mso.fail_json(msg=not_found_contracts)
-       elif not mso.existing:
+       elif contract and not mso.existing:
            mso.fail_json(msg="Contract with Reference '{0}' and type '{1}' not found".format(contract_ref, contract.get("type")))
        mso.exit_json()
```

**Comment by akinross** [comment]
Hi @justinbrink, thank you for raising the bug. I have linked your PR to the issue and have assigned our team to review.
